services:
  api:
    build: .
    container_name: api_agropec
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/agropec
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      JWT_SECRET: 22446688
    
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agropec
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d agropec"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - 5432

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    networks:
      - internal
    expose:
      - 9000
      - 9001

volumes:
  pgdata:
  miniodata:

networks:
  internal:
    driver: bridge
